-- 1
DECLARE
    NUM NUMBER := &num;
    NEGATIVE_NUMBER EXCEPTION;

BEGIN
    IF NUM < 0 THEN
        RAISE NEGATIVE_NUMBER;
    END IF;
    DBMS_OUTPUT.PUT_LINE('Positivo: ' || NUM);

EXCEPTION
    WHEN NEGATIVE_NUMBER THEN
    DBMS_OUTPUT.PUT_LINE('Negativo: ' || NUM);

END;
/


-- 2
CREATE OR REPLACE PROCEDURE SUBIR_SALARIO(
    V_EMP_NO NUMBER, CANTIDAD NUMBER
)
IS
    SALARY_IS_NULL EXCEPTION;
    V_SALARIO EMPLE.SALARIO%TYPE;

BEGIN
    SELECT SALARIO INTO V_SALARIO
        FROM EMPLE
        WHERE V_EMP_NO = EMP_NO;

    IF V_SALARIO IS NULL THEN
        RAISE SALARY_IS_NULL;
    END IF;

    UPDATE EMPLE
        SET SALARIO = SALARIO + CANTIDAD
        WHERE V_EMP_NO = EMP_NO;

EXCEPTION
    WHEN SALARY_IS_NULL THEN
        DBMS_OUTPUT.PUT_LINE('El salario del empleado es nulo');
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No se ha encontrado el num. del empleado');
    
END;
/
EXECUTE SUBIR_SALARIO(9999, 100);


-- 3
CREATE OR REPLACE PROCEDURE CREAR_EMPLEADO(
    V_EMP_NO NUMBER, V_APELLIDO VARCHAR, V_OFICIO VARCHAR, V_DIR NUMBER, V_FECHA_ALT DATE, V_SALARIO NUMBER, V_COMISION NUMBER, V_DEPT_NO NUMBER
)
IS
    NO_DIR_FOUND EXCEPTION;
    DEPARTAMENTO DEPART.DEPT_NO%TYPE;

BEGIN
    SELECT DEPT_NO INTO DEPARTAMENTO
        FROM DEPART
        WHERE V_DEPT_NO = DEPT_NO;

    IF V_DIR IS NULL THEN
        RAISE NO_DIR_FOUND;
    END IF; 

    INSERT INTO EMPLE VALUES(V_EMP_NO, V_APELLIDO, V_OFICIO, V_DIR, V_FECHA_ALT, V_SALARIO, V_COMISION, V_DEPT_NO);

    DBMS_OUTPUT.PUT_LINE('Empleado creado correctamente');

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No se ha encontrado el dept. ' || V_DEPT_NO);
    WHEN NO_DIR_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No se ha encontrado el director ' || V_DIR);
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('El num. del empleado ya existe');

END;
/
EXECUTE CREAR_EMPLEADO(9998, 'JASON', 'JEFE', 9999, '25/04/2022', 1500, NULL, 50);
EXECUTE CREAR_EMPLEADO(9998, 'JASON', 'JEFE', NULL, '25/04/2022', 1500, NULL, 40);
EXECUTE CREAR_EMPLEADO(9999, 'JASON', 'JEFE', 9999, '25/04/2022', 1500, NULL, 40);
EXECUTE CREAR_EMPLEADO(9998, 'JASON', 'JEFE', 9999, '25/04/2022', 1500, NULL, 40);


-- 4
CREATE OR REPLACE PROCEDURE CREAR_DEPT(
    V_DEPT_NO NUMBER, V_DNOMBRE VARCHAR, V_LOC VARCHAR
)
IS
BEGIN
    INSERT INTO DEPART VALUES(V_DEPT_NO, UPPER(V_DNOMBRE), UPPER(V_LOC));

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('Departamento ya existente');

END;
/
EXECUTE CREAR_DEPT(40, 'MARKETING', 'MURCIA');
EXECUTE CREAR_DEPT(50, 'CONTABILIDAD', 'MURCIA');
EXECUTE CREAR_DEPT(50, 'MARKETING', 'MURCIA');


-- 5
CREATE OR REPLACE PROCEDURE DIVIDIR(
    DIVIDENDO NUMBER, DIVISOR NUMBER
)
IS
BEGIN
    IF DIVISOR = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'No puedes dividir por 0');
    END IF;
    DBMS_OUTPUT.PUT_LINE(DIVIDENDO / DIVISOR);

EXCEPTION
    -- WHEN ZERO_DIVIDE THEN
        -- DBMS_OUTPUT.PUT_LINE('ERROR: Division por cero');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
        
END;
/
EXECUTE DIVIDIR(10, 0);
EXECUTE DIVIDIR(10, 5);


-- 6
CREATE OR REPLACE PROCEDURE CREAR_EMPLEADO(
    V_EMP_NO NUMBER, V_APELLIDO VARCHAR, V_OFICIO VARCHAR, V_DIR NUMBER, V_FECHA_ALT DATE, V_SALARIO NUMBER, V_COMISION NUMBER, V_DEPT_NO NUMBER
)
IS
    NO_DIR_FOUND EXCEPTION;
    DEPARTAMENTO DEPART.DEPT_NO%TYPE;

BEGIN
    IF V_DIR IS NULL THEN
        RAISE NO_DIR_FOUND;
    END IF;

    IF V_DEPT_NO IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se ha encontrado depto.');
    END IF; 

    INSERT INTO EMPLE VALUES(V_EMP_NO, V_APELLIDO, V_OFICIO, V_DIR, V_FECHA_ALT, V_SALARIO, V_COMISION, V_DEPT_NO);

    DBMS_OUTPUT.PUT_LINE('Empleado creado correctamente');

EXCEPTION
    WHEN NO_DIR_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No se ha encontrado el director ' || V_DIR);
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('El num. del empleado ya existe');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);

END;
/
EXECUTE CREAR_EMPLEADO(9998, 'JASON', 'JEFE', 9999, '25/04/2022', 1500, NULL, NULL);
EXECUTE CREAR_EMPLEADO(9998, 'JASON', 'JEFE', NULL, '25/04/2022', 1500, NULL, 40);
EXECUTE CREAR_EMPLEADO(9999, 'JASON', 'JEFE', 9999, '25/04/2022', 1500, NULL, 40);
EXECUTE CREAR_EMPLEADO(9998, 'JASON', 'JEFE', 9999, '25/04/2022', 1500, NULL, 40);


-- 7
CREATE OR REPLACE PROCEDURE CREAR_DEPT(
    V_DNOMBRE VARCHAR, V_LOC VARCHAR
)
IS
    ULTIMO_DEPT DEPART.DEPT_NO%TYPE;

BEGIN
    SELECT MAX(DEPT_NO) INTO ULTIMO_DEPT
        FROM DEPART;

    INSERT INTO DEPART VALUES(10 + ULTIMO_DEPT, UPPER(V_DNOMBRE), UPPER(V_LOC));

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('Departamento ya existente');

END;
/
EXECUTE CREAR_DEPT('CONTABILIDAD', 'PALENCIA');
EXECUTE CREAR_DEPT('RRHH', 'PALENCIA');
EXECUTE CREAR_DEPT('I+D', 'KOSOVO');