SET HEADSEP |
SET PAGESIZE 30
SET LINESIZE 100
SET VERIFY OFF

ACCEPT N_PEDIDO PROMPT 'INTRODUZCA EL NUMERO DE PEDIDO A LISTAR (PEDX):'

TTITLE 'CIF:S02021943.'-
SKIP 1 'DEEP PURPLE S.A.'-
SKIP 1 'C/LUDOVICO. 28019. MADRID.'-
SKIP 2

COLUMN N_PEDIDO HEADING 'NUMERO DE PEDIDO:' FORMAT A20
COLUMN FECHA_PED HEADING 'FECHA:'

COLUMN NOMBRE_C HEADING 'CLIENTE:' FORMAT A30
COLUMN DIRECCION_C HEADING 'DIRECCION:'

COLUMN NOMBRE_P HEADING 'PRODUCTO'
COLUMN CANTIDAD HEADING 'CANTIDAD'
COLUMN PRECIO HEADING 'PRECIO POR UNIDAD'

SELECT N_PEDIDO, FECHA_PED FROM CAB_PEDIDO 
WHERE &N_PEDIDO=N_PEDIDO 
ORDER BY N_PEDIDO;
TTITLE OFF

SELECT NOMBRE_C, DIRECCION_C FROM CLIENTE, CAB_PEDIDO 
WHERE &N_PEDIDO=N_PEDIDO 
AND CLIENTE.DNI=CAB_PEDIDO.DNI;

SELECT NOMBRE_P, CANTIDAD, PRECIO FROM PRODUCTO, LINEA_PEDIDO 
WHERE &N_PEDIDO=N_PEDIDO 
AND PRODUCTO.CODIGO_P=LINEA_PEDIDO.CODIGO_P 
ORDER BY N_LINEA_PEDIDO;

CLEAR BREAK
CLEAR COLUMN 
CLEAR COMPUTES


