SET HEADSEP |
SET PAGESIZE 300
SET LINESIZE 300
SET VERIFY OFF

ACCEPT NUM_FACT PROMPT 'INTRODUZCA EL NUMERO DE FACTURA A LISTAR (FACX):'

TTITLE 'CIF:S02021943.'-
SKIP 1 'DEEP PURPLE S.A.'-
SKIP 1 'C/LUDOVICO. 28019. MADRID.'-
SKIP 2

COMPUTE SUM LABEL 'TOTAL GENERAL' OF 'TOTAL' ON REPORT
COMPUTE SUM OF 'TOTAL CON IVA' ON  REPORT
BREAK ON REPORT SKIP 

SET LINESIZE 300
SET PAGESIZE 300
SET NEWPAGE 1

COLUMN NUM_FACT HEADING 'FACTURA:' FORMAT A20
COLUMN FECHA_FACT HEADING 'FECHA:'

COLUM NOMBRE_C HEADING 'CLIENTE:' FORMAT A30
COLUMN DIRECCION_C HEADING 'DIRECCION:'

COLUMN NOMBRE_P HEADING 'PRODUCTO'
COLUMN CANTIDAD HEADING 'CANT_ALB' FORMAT A9
COLUMN PRECIO HEADING 'PRECIO UNITARIO'

COLUMN (PRODUCTO.PRECIO*LINEA_ALBARAN.CANTIDAD) HEADING 'TOTAL'
COLUMN ((PRODUCTO.PRECIO*LINEA_ALBARAN.CANTIDAD)*IVA) HEADING 'TOTAL CON IVA'

SELECT NUM_FACT, FECHA_FACT FROM FACTURA WHERE &NUM_FACT=NUM_FACT ORDER BY NUM_FACT;

TTITLE OFF

SELECT DISTINCT CLIENTE.NOMBRE_C, DIRECCION_C 
FROM CLIENTE, CAB_PEDIDO, CAB_ALBARAN, FACTURA 
WHERE FACTURA.NUM_FACT=&NUM_FACT 
AND CLIENTE.DNI=CAB_PEDIDO.DNI 
AND CAB_PEDIDO.N_PEDIDO=CAB_ALBARAN.N_PEDIDO 
AND FACTURA.NUM_FACT=CAB_ALBARAN.NUM_FACT;

SELECT PRODUCTO.NOMBRE_P, LINEA_ALBARAN.CANTIDAD, PRODUCTO.PRECIO, (PRODUCTO.PRECIO*LINEA_ALBARAN.CANTIDAD) "TOTAL", (((PRODUCTO.PRECIO*LINEA_ALBARAN.CANTIDAD)*IVA)) "TOTAL CON IVA" 
FROM PRODUCTO, LINEA_ALBARAN, FACTURA, CAB_ALBARAN, CAB_PEDIDO, CLIENTE WHERE FACTURA.NUM_FACT=&NUM_FACT 
AND PRODUCTO.CODIGO_P=LINEA_ALBARAN.CODIGO_P
AND FACTURA.NUM_FACT=CAB_ALBARAN.NUM_FACT
AND CAB_ALBARAN.N_ALBARAN=LINEA_ALBARAN.N_ALBARAN
AND CAB_PEDIDO.N_PEDIDO=CAB_ALBARAN.N_PEDIDO
AND CLIENTE.DNI=CAB_PEDIDO.DNI;

CLEAR BREAK
CLEAR COLUMN 
CLEAR COMPUTES