DROP TABLE EMPRESA CASCADE CONSTRAINT;
CREATE TABLE EMPRESA(
  CIF VARCHAR2 (9) PRIMARY KEY,
  NOMBRE VARCHAR2 (17) NOT NULL,
  DIRECCION_E VARCHAR2 (50)NOT NULL,
  TELEFONO VARCHAR2 (9) NOT NULL
);

DROP TABLE PRODUCTO CASCADE CONSTRAINT;
CREATE TABLE PRODUCTO(
  CODIGO_P VARCHAR2 (9) PRIMARY KEY,
  NOMBRE_P VARCHAR2 (20) NOT NULL,
  PRECIO NUMBER (5) NOT NULL,
  CIF VARCHAR2 (9) NOT NULL,
  CONSTRAINT FK_PRODUCTO FOREIGN KEY(CIF) REFERENCES EMPRESA(CIF) ON DELETE CASCADE
);

DROP TABLE CLIENTE CASCADE CONSTRAINT;
CREATE TABLE CLIENTE (
  DNI VARCHAR2 (9) PRIMARY KEY,
  NOMBRE_C VARCHAR2 (40) NOT NULL,
  DIRECCION_C VARCHAR2 (15) NOT NULL,
  TELEFONO NUMBER(9) NOT NULL
);

DROP TABLE CAB_PEDIDO CASCADE CONSTRAINT;
CREATE TABLE CAB_PEDIDO (
  N_PEDIDO VARCHAR2 (4) PRIMARY KEY,
  FECHA_PED DATE NOT NULL,
  DNI VARCHAR2 (9),
  CONSTRAINT FK_DNI FOREIGN KEY(DNI) REFERENCES CLIENTE(DNI) ON DELETE CASCADE
);

DROP TABLE LINEA_PEDIDO CASCADE CONSTRAINT;
CREATE TABLE LINEA_PEDIDO(
  N_LINEA_PEDIDO VARCHAR2 (3) NOT NULL,
  N_PEDIDO VARCHAR2 (4) NOT NULL,
  CODIGO_P VARCHAR2 (9) NOT NULL,
  CANTIDAD NUMBER (5) NOT NULL,
  CONSTRAINT PK_LINEAPEDIDO PRIMARY KEY(N_LINEA_PEDIDO,N_PEDIDO),
  CONSTRAINT FK_LINEAPEDIDO1 FOREIGN KEY(CODIGO_P) REFERENCES PRODUCTO(CODIGO_P) ON DELETE CASCADE,
  CONSTRAINT FK_LINEAPEDIDO2 FOREIGN KEY(N_PEDIDO) REFERENCES CAB_PEDIDO(N_PEDIDO) ON DELETE CASCADE
);

DROP TABLE FACTURA CASCADE CONSTRAINT;
CREATE TABLE FACTURA (
  NUM_FACT VARCHAR2 (4) PRIMARY KEY,
  FECHA_FACT DATE NOT NULL,
  IVA DECIMAL (11,2) NOT NULL
);

DROP TABLE CAB_ALBARAN CASCADE CONSTRAINT;
CREATE TABLE CAB_ALBARAN(
  N_ALBARAN VARCHAR2 (4) PRIMARY KEY,
  N_PEDIDO VARCHAR2 (4) NOT NULL,
  NUM_FACT VARCHAR2 (4) NOT NULL,
  FECHA_ALB DATE NOT NULL,
  CONSTRAINT FK_CABALBAR1 FOREIGN KEY(N_PEDIDO) REFERENCES CAB_PEDIDO(N_PEDIDO) ON DELETE CASCADE,
  CONSTRAINT FK_CABALBAR2 FOREIGN KEY(NUM_FACT) REFERENCES FACTURA(NUM_FACT) ON DELETE CASCADE
);

DROP TABLE LINEA_ALBARAN CASCADE CONSTRAINT;
CREATE TABLE LINEA_ALBARAN(
  N_LINEA_ALBARAN VARCHAR2 (3) NOT NULL,
  N_ALBARAN VARCHAR2 (4) NOT NULL,
  CODIGO_P VARCHAR2 (9) NOT NULL,
  CANTIDAD VARCHAR2 (4) NOT NULL,
  CONSTRAINT PK_LINEAALBAR PRIMARY KEY(N_LINEA_ALBARAN,N_ALBARAN),
  CONSTRAINT FK_LINEAALBAR FOREIGN KEY(N_ALBARAN) REFERENCES CAB_ALBARAN(N_ALBARAN) ON DELETE CASCADE,
  CONSTRAINT FK_LINEAALBAR1 FOREIGN KEY(CODIGO_P) REFERENCES PRODUCTO(CODIGO_P) ON DELETE CASCADE
 );
COMMIT;


