SET HEADSEP |
SET PAGESIZE 100
SET LINESIZE 50
SET VERIFY OFF

TTITLE '=====================| LISTA DE PRODUCTOS |====================='
COLUMN CODIGO_P HEADING 'CODIGO'
COLUMN NOMBRE_P HEADING 'NOMBRE'
COLUMN PRECIO HEADING 'PRECIO'

SELECT CODIGO_P, NOMBRE_P, PRECIO FROM PRODUCTO ORDER BY CODIGO_P ASC;
TTITLE OFF
SET FEEDBACK OFF
