SET HEADSEP |
SET PAGESIZE 30
SET LINESIZE 100
SET VERIFY OFF

ACCEPT N_ALBARAN PROMPT 'INTRODUZCA EL NUMERO DE ALBARAN A LISTAR (ALBX):'

TTITLE  'CIF:S02021943.'-
SKIP 1  'DEEP PURPLE S.A.'-
SKIP 1  'C/LUDOVICO. 28019. MADRID.'-
SKIP 2

COLUMN N_ALBARAN HEADING 'NUMERO DE ALBARAN:' FORMAT A20
COLUMN FECHA_ALB HEADING 'FECHA:'

COLUMN NOMBRE_C HEADING 'CLIENTE' FORMAT A30
COLUMN DIRECCION_C HEADING 'DIRECCION'

COLUMN NOMBRE_P HEADING 'PRODUCTO'
COLUMN CANTIDAD HEADING 'CANTIDAD' FORMAT A9
COLUMN PRECIO HEADING 'PRECIO UNITARIO'

SELECT N_ALBARAN, FECHA_ALB FROM CAB_ALBARAN WHERE &N_ALBARAN=N_ALBARAN ORDER BY N_ALBARAN;
TTITLE OFF
SELECT NOMBRE_C, DIRECCION_C FROM CLIENTE, CAB_PEDIDO, CAB_ALBARAN WHERE &N_ALBARAN=N_ALBARAN AND CLIENTE.DNI=CAB_PEDIDO.DNI AND CAB_PEDIDO.N_PEDIDO=CAB_ALBARAN.N_PEDIDO;
SELECT NOMBRE_P, CANTIDAD, PRECIO FROM PRODUCTO, LINEA_ALBARAN WHERE &N_ALBARAN=N_ALBARAN AND PRODUCTO.CODIGO_P=LINEA_ALBARAN.CODIGO_P ORDER BY N_LINEA_ALBARAN;

CLEAR BREAK
CLEAR COLUMN 
CLEAR COMPUTES
