DROP TABLE LIBROS;
CREATE TABLE LIBROS(
    CODIGO NUMBER(3),
    TITULO VARCHAR2(40),
    AUTOR VARCHAR2(30),
    PRECIO NUMBER(5,2)
);

INSERT INTO LIBROS VALUES(100,'Uno','Richard Bach',15);
INSERT INTO LIBROS VALUES(300,'Aprenda PHP','Mario Molina',55);
INSERT INTO LIBROS VALUES(102,'Matematica estas ahi','Paenza',18);
INSERT INTO LIBROS VALUES(105,'El aleph','Borges',25);
INSERT INTO LIBROS VALUES(109,'El experto en laberintos','Gaskin',20);
INSERT INTO LIBROS VALUES(204,'Alicia en el pais de las 
maravillas','Carroll',31);


-- 1
CREATE OR REPLACE FUNCTION INCREMENTAR_10(
    VALOR NUMBER
)
RETURN NUMBER
IS
BEGIN
    RETURN VALOR * 1.10;

END;
/
SELECT TITULO, PRECIO, INCREMENTAR_10(PRECIO) "PRECIO + 10%" FROM LIBROS;


-- 2
CREATE OR REPLACE FUNCTION INCREMENTAR(
    VALOR NUMBER, INCREMENTO NUMBER
)
RETURN NUMBER
IS
    PORCENTAJE NUMBER := 1 + (INCREMENTO / 100);
    
BEGIN
    RETURN VALOR * PORCENTAJE;

END;
/
SELECT TITULO, PRECIO, INCREMENTAR(PRECIO, 20) "PRECIO + 20%" FROM LIBROS;

SELECT TITULO, PRECIO, INCREMENTAR(PRECIO, 100) "PRECIO + 100%" FROM LIBROS;


-- 3
CREATE OR REPLACE FUNCTION TIPO(
    NUM NUMBER
)
RETURN VARCHAR2
IS
BEGIN
    IF NUM <= 20 THEN
        RETURN 'ECONOMICO';
    ELSE
        RETURN 'COSTOSO';
    END IF;

END;
/

COLUMN TITULO HEADING 'TITULO' FORMAT A40
COLUMN PRECIO HEADING 'PRECIO' FORMAT 99999,99
COLUMN TIPO HEADING 'TIPO' FORMAT A9

SELECT TITULO, PRECIO, TIPO(PRECIO) "TIPO" FROM LIBROS;

CLEAR COLUMNS



