ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY';

DROP TABLE FACTURA CASCADE CONSTRAINT;
CREATE TABLE FACTURA(
    NUMERO VARCHAR2(4) PRIMARY KEY,
    FECHA DATE NOT NULL,
    IVA NUMBER(3) NOT NULL
);

DROP TABLE CLIENTE CASCADE CONSTRAINT;
CREATE TABLE CLIENTE(
    DNI VARCHAR2(9) PRIMARY KEY,
    NOMBRE VARCHAR2(15) NOT NULL,
    DIRECCION VARCHAR2(20) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL
);

DROP TABLE CABECERA_PEDIDO CASCADE CONSTRAINT;
CREATE TABLE CABECERA_PEDIDO(
    NUM_PEDIDO VARCHAR2(4) PRIMARY KEY,
    FECHA DATE NOT NULL,
    DNI VARCHAR2(9) NOT NULL, 
    CONSTRAINT FK_DNI_PED FOREIGN KEY (DNI) REFERENCES CLIENTE(DNI) ON DELETE CASCADE
);

DROP TABLE CABECERA_ALBARAN CASCADE CONSTRAINT;
CREATE TABLE CABECERA_ALBARAN(
    NUM_ALBARAN VARCHAR2(9) PRIMARY KEY,
    FECHA DATE NOT NULL,
    NUM_PEDIDO VARCHAR2(4) NOT NULL,
    NUMERO_FACT VARCHAR2(4) NOT NULL,
    CONSTRAINT FK_ALB_PED FOREIGN KEY (NUM_PEDIDO) REFERENCES CABECERA_PEDIDO(NUM_PEDIDO) ON DELETE CASCADE,
    CONSTRAINT FK_ALB_FAC FOREIGN KEY (NUMERO_FACT) REFERENCES FACTURA(NUMERO) ON DELETE CASCADE
);

DROP TABLE EMPRESA CASCADE CONSTRAINT;
CREATE TABLE EMPRESA(
    CIF VARCHAR2(9) PRIMARY KEY,
    NOMBRE VARCHAR2(20) NOT NULL,
    DIRECCION VARCHAR2(20) NOT NULL
);

DROP TABLE PRODUCTOS CASCADE CONSTRAINT;
CREATE TABLE PRODUCTOS(
    CODIGO VARCHAR2(9) PRIMARY KEY,
    NOMBRE VARCHAR2(15) NOT NULL,
    PRECIO NUMBER(4,2) NOT NULL,
    CIF VARCHAR2(9) NOT NULL,
    CONSTRAINT FK_PROD_EMP FOREIGN KEY (CIF) REFERENCES EMPRESA(CIF) ON DELETE CASCADE
);

DROP TABLE LINEA_PEDIDO CASCADE CONSTRAINT;
CREATE TABLE LINEA_PEDIDO(
    NUM_LINEA VARCHAR2(2) NOT NULL,
    CANTIDAD NUMBER(4) NOT NULL,
    NUM_PEDIDO VARCHAR2(4) NOT NULL,
    COD_PRODUCTO VARCHAR2(9) NOT NULL,
    CONSTRAINT FK_LINPED_PED FOREIGN KEY (NUM_PEDIDO) REFERENCES CABECERA_PEDIDO(NUM_PEDIDO) ON DELETE CASCADE,
    CONSTRAINT FK_LINPED_PROD FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTOS(CODIGO) ON DELETE CASCADE,
    CONSTRAINT PK_LINEA_PED PRIMARY KEY (NUM_PEDIDO, NUM_LINEA, COD_PRODUCTO)
);

DROP TABLE LINEA_ALBARAN CASCADE CONSTRAINT;
CREATE TABLE LINEA_ALBARAN(
    NUM_LINEA VARCHAR2(2) NOT NULL,
    CANTIDAD NUMBER(4) NOT NULL,
    NUM_ALBARAN VARCHAR2(9) NOT NULL,
    COD_PROD VARCHAR2(9) NOT NULL,
    CONSTRAINT FK_LINALB_PROD FOREIGN KEY (COD_PROD) REFERENCES PRODUCTOS(CODIGO) ON DELETE CASCADE,
    CONSTRAINT FK_LINALB_CABALB FOREIGN KEY (NUM_ALBARAN) REFERENCES CABECERA_ALBARAN(NUM_ALBARAN) ON DELETE CASCADE,
    CONSTRAINT PK_LINALB PRIMARY KEY (NUM_ALBARAN, NUM_LINEA, COD_PROD)
);