SET WRAP OFF
SET VERIFY OFF
SET PAGESIZE 66
SET LINESIZE 120

ACCEPT CABECERA_PEDIDO PROMPT 'Introduzca el número de pedido a listar (PEDXX): '
TTITLE LEFT 'CIF: 1234560MJ'-
SKIP 1 'TRANS KINGS'-
SKIP 1 'AV REYES MAGOS 1, 2009, MADRID'

COLUMN NUM_PEDIDO 'Numero de pedido' A20
COLUMN FECHA 'Fecha' A12

