SET WRAP OFF
SET VERIFY OFF
SET PAGESIZE 66
SET LINESIZE 120

ACCEPT CABECERA_PEDIDO PROMPT 'Introduzca el número de pedido a listar (PEDXX): '
TTITLE LEFT 'CIF: 1234560MJ'-
SKIP 1 'TRANS KINGS'-
SKIP 1 'AV REYES MAGOS 1, 2009, MADRID'
SKIP 1

COLUMN NUM_PEDIDO HEADING 'Numero de pedido' A20
COLUMN FECHA HEADING 'Fecha'
COLUMN NOMBRE HEADING 'Cliente' A12
COLUMN DIRECCION HEADING 'Dirección' A12
COLUMN NOMBRE HEADING 'Producto' A12
COLUMN CANTIDAD HEADING 'Cantidad' A4
COLUMN PRECIO HEADING 'Precio unitario' A5 

SELECT NUM_PEDIDO, FECHA FROM CABECERA_PEDIDO WHERE &NUM_PEDIDO=NUM_PEDIDO ORDER BY NUM_PEDIDO;
TTITLE OFF

SELECT C.NOMBRE, C.DIRECCION FROM CLIENTE C, CABECERA_PEDIDO P WHERE &NUM_PEDIDO=NUM_PEDIDO AND CLIENTE.DNI=CAB_PEDIDO.DNI;

SELECT NOMBRE_P, CANTIDAD, PRECIO FROM PRODUCTO, LINEA_PEDIDO WHERE &N_PEDIDO=N_PEDIDO AND PRODUCTO.CODIGO_P=LINEA_PEDIDO.CODIGO_P ORDER BY N_LINEA_PEDIDO;

CLEAR BREAK
CLEAR COLUMN 
CLEAR COMPUTES
