SET COLSEP 
SET WRAP OFF
SET VERIFY OFF
SET PAGESIZE 266
SET LINESIZE 266

ACCEPT NUMERO PROMPT 'INTRODUZCA EL NUMERO DE FACTURA A LISTAR (FACX):'

TTITLE 'CIF: 1234560MJ'-
SKIP 1 'TRANS KINGS'-
SKIP 1 'AV REYES MAGOS 1, 2009, MADRID'-
SKIP 2

COMPUTE SUM LABEL 'TOTAL GENERAL' OF 'TOTAL' ON REPORT
COMPUTE SUM OF 'TOTAL CON IVA' ON  REPORT
BREAK ON REPORT SKIP 

SET LINESIZE 266
SET PAGESIZE 266
SET NEWPAGE 1

COLUMN NUMERO HEADING 'FACTURA:' FORMAT A20
COLUMN FECHA HEADING 'FECHA:'

COLUM NOMBRE HEADING 'CLIENTE:' FORMAT A30
COLUMN DIRECCION HEADING 'DIRECCION:'

COLUMN NOMBRE HEADING 'PRODUCTO'
COLUMN CANTIDAD HEADING 'CANT_ALB' FORMAT A9
COLUMN PRECIO HEADING 'PRECIO UNITARIO'

COLUMN (PRODUCTO.PRECIO*LINEA_ALBARAN.CANTIDAD) HEADING 'TOTAL'
COLUMN ((PRODUCTO.PRECIO*LINEA_ALBARAN.CANTIDAD)*IVA) HEADING 'TOTAL CON IVA'

SELECT NUMERO, FECHA FROM FACTURA WHERE &NUMERO=NUMERO ORDER BY NUMERO;

TTITLE OFF

SELECT DISTINCT C.NOMBRE, C.DIRECCION 
FROM CLIENTE C, CAB_PEDIDO PED, CAB_ALBARAN A, FACTURA F
WHERE F.NUMERO=&F.NUMERO
AND C.DNI=PED.DNI 
AND PED.NUM_PEDIDO=A.NUM_PEDIDO 
AND F.NUMERO=A.NUMERO;

SELECT PRODUCTO.NOMBRE, LINEA_ALBARAN.CANTIDAD, PRODUCTO.PRECIO, (PRODUCTO.PRECIO*LINEA_ALBARAN.CANTIDAD) "TOTAL", (((PRODUCTO.PRECIO*LINEA_ALBARAN.CANTIDAD)*IVA)) "TOTAL CON IVA" 
FROM PRODUCTO, LINEA_ALBARAN, FACTURA, CAB_ALBARAN, CAB_PEDIDO, CLIENTE WHERE FACTURA.NUMERO=&NUMERO 
AND PRODUCTO.CODIGO_P=LINEA_ALBARAN.CODIGO_P
AND FACTURA.NUMERO=CAB_ALBARAN.NUMERO
AND CAB_ALBARAN.N_ALBARAN=LINEA_ALBARAN.N_ALBARAN
AND CAB_PEDIDO.N_PEDIDO=CAB_ALBARAN.N_PEDIDO
AND CLIENTE.DNI=CAB_PEDIDO.DNI;

CLEAR BREAK
CLEAR COLUMN 
CLEAR COMPUTES