SET WRAP OFF
SET VERIFY OFF
SET PAGESIZE 66
SET LINESIZE 120

ACCEPT CABECERA_PEDIDO PROMPT 'Introduzca el número de pedido a listar (PEDXX): '
TTITLE LEFT 'CIF: 1234560MJ'-
SKIP 1 'TRANS KINGS'-
SKIP 1 'AV REYES MAGOS 1, 2009, MADRID'
SKIP 2

COLUMN NUM_PEDIDO HEADING 'Numero de pedido' A20
COLUMN FECHA HEADING 'Fecha'
COLUMN NOMBRE HEADING 'Cliente' A12
COLUMN DIRECCION HEADING 'Dirección' A12
COLUMN NOMBRE HEADING 'Producto' A12
COLUMN CANTIDAD HEADING 'Cantidad' A4
COLUMN PRECIO HEADING 'Precio unitario' A5 

SELECT NUM_PEDIDO, FECHA FROM CABECERA_PEDIDO WHERE &NUM_PEDIDO=NUM_PEDIDO ORDER BY NUM_PEDIDO;
TTITLE OFF

SELECT C.NOMBRE, C.DIRECCION FROM CLIENTE C, CABECERA_PEDIDO P WHERE &P.NUM_PEDIDO=P.NUM_PEDIDO AND C.DNI=P.DNI;

SELECT PR.NOMBRE, PED.CANTIDAD, PR.PRECIO FROM PRODUCTO PR, LINEA_PEDIDO PED 
WHERE &NUM_PEDIDO=NUM_PEDIDO AND PR.CODIGO=PED.COD_PRODUCTO ORDER BY NUM_LINEA;

CLEAR BREAK
CLEAR COLUMN 
CLEAR COMPUTES
