SET COLSEP 
SET WRAP OFF
SET VERIFY OFF
SET PAGESIZE 66
SET LINESIZE 120

ACCEPT NUM_ALBARAN PROMPT 'INTRODUZCA EL NUMERO DE ALBARAN A LISTAR (ALBX):'

TTITLE  'CIF: 1234560MJ'-
SKIP 1  'TRANS KINGS'-
SKIP 1  'AV REYES MAGOS 1, 2009, MADRID'-
SKIP 2

COLUMN NUM_ALBARAN HEADING 'NUMERO DE ALBARAN:' FORMAT A20
COLUMN FECHA HEADING 'FECHA:'
COLUMN NOMBRE HEADING 'CLIENTE' FORMAT A30
COLUMN DIRECCION HEADING 'DIRECCION'
COLUMN NOMBRE HEADING 'PRODUCTO'
COLUMN CANTIDAD HEADING 'CANTIDAD' FORMAT A9
COLUMN PRECIO HEADING 'PRECIO UNITARIO'

SELECT NUM_ALBARAN, FECHA FROM CABECERA_ALBARAN 
WHERE &NUM_ALBARAN=NUM_ALBARAN ORDER BY NUM_ALBARAN;
TTITLE OFF

SELECT C.NOMBRE, C.DIRECCION FROM CLIENTE C, CABECERA_PEDIDO PED, CABECERA_ALBARAN A WHERE &A.NUM_ALBARAN=A.NUM_ALBARAN AND C.DNI=PED.DNI AND PED.NUM_PEDIDO=A.NUM_PEDIDO;

SELECT NOMBRE, CANTIDAD, PRECIO FROM PRODUCTO PR, LINEA_ALBARAN A WHERE &A.NUM_ALBARAN=A.NUM_ALBARAN AND PR.CODIGO=A.COD_PROD ORDER BY A.NUM_LINEA;

CLEAR BREAK
CLEAR COLUMN 
CLEAR COMPUTES