SET COLSEP 
SET WRAP OFF
SET VERIFY OFF
SET PAGESIZE 66
SET LINESIZE 120



TTITLE LEFT 'Listado de productos'-
SKIP 1 '===================='
COLUMN CODIGO 'Código' A12
COLUMN NOMBRE 'Nombre' A12
COLUMN PRECIO 'Precio' 999D999G99
SELECT CODIGO, NOMBRE, PRECIO FROM PRODUCTOS;